-- grcg6a PostgreSQL Schema
-- SQLite → PostgreSQL Migration
-- 14 tables, 依赖顺序: chromosome → gene_xref → go_term → gene_go → ...
--
-- 运行说明:
--   方式1: docker-compose up -d postgres  (自动通过 001_schema.sql 初始化空卷)
--   方式2: psql -h localhost -U grcuser -d grcg6a -f db/schema.sql

BEGIN;

-- ========================================================================
-- 1. chromosome
-- ========================================================================
CREATE TABLE IF NOT EXISTS chromosome (
    seqid        TEXT PRIMARY KEY,
    chr_name     TEXT,
    length       BIGINT NOT NULL,
    description  TEXT
);

-- ========================================================================
-- 2. gene_xref
-- seqid/gene_start/gene_end/gene_strand/gene_biotype 从 SQLite 迁移时可选，
-- 有则迁，无则为 NULL。
-- ========================================================================
CREATE TABLE IF NOT EXISTS gene_xref (
    gene_id               TEXT PRIMARY KEY,
    gene_symbol           TEXT,
    ncbi_gene_id          TEXT,
    ensembl_gene_id       TEXT,
    ensembl_transcript_id  TEXT,
    seqid                 TEXT REFERENCES chromosome(seqid) ON DELETE SET NULL,
    gene_start            BIGINT,
    gene_end              BIGINT,
    gene_strand           TEXT,
    gene_biotype          TEXT,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gene_xref_gene_symbol    ON gene_xref(gene_symbol);
CREATE INDEX IF NOT EXISTS idx_gene_xref_ncbi_gene_id   ON gene_xref(ncbi_gene_id);
CREATE INDEX IF NOT EXISTS idx_gene_xref_ensembl_gene_id ON gene_xref(ensembl_gene_id);
CREATE INDEX IF NOT EXISTS idx_gene_xref_seqid           ON gene_xref(seqid);

-- ========================================================================
-- 3. go_term  (GO 术语字典，从 gene_go 提取唯一术语)
-- ========================================================================
CREATE TABLE IF NOT EXISTS go_term (
    go_id         TEXT PRIMARY KEY,
    go_name       TEXT,
    go_namespace  TEXT,
    go_definition TEXT
);

CREATE INDEX IF NOT EXISTS idx_go_term_namespace ON go_term(go_namespace);

-- ========================================================================
-- 4. gene_go  (去冗余：不含 go_name/go_namespace/go_definition)
-- ========================================================================
CREATE TABLE IF NOT EXISTS gene_go (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gene_id       TEXT NOT NULL REFERENCES gene_xref(gene_id) ON DELETE CASCADE,
    go_id         TEXT NOT NULL REFERENCES go_term(go_id) ON DELETE CASCADE,
    evidence_code TEXT,
    source        TEXT,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(gene_id, go_id, evidence_code)
);

CREATE INDEX IF NOT EXISTS idx_gene_go_gene_id ON gene_go(gene_id);
CREATE INDEX IF NOT EXISTS idx_gene_go_go_id  ON gene_go(go_id);

-- ========================================================================
-- 5. gene_kegg
-- ========================================================================
CREATE TABLE IF NOT EXISTS gene_kegg (
    gene_id       TEXT PRIMARY KEY REFERENCES gene_xref(gene_id) ON DELETE CASCADE,
    gene_symbol   TEXT,
    ncbi_gene_id  TEXT,
    kegg_gene_id  TEXT
);

CREATE INDEX IF NOT EXISTS idx_gene_kegg_kegg_gene_id ON gene_kegg(kegg_gene_id);

-- ========================================================================
-- 6. kegg_pathway_asset
-- ========================================================================
CREATE TABLE IF NOT EXISTS kegg_pathway_asset (
    pathway_id      TEXT PRIMARY KEY,
    pathway_name    TEXT,
    pathway_class   TEXT,
    png_filename    TEXT,
    png_relpath     TEXT,
    png_url         TEXT,
    png_file_size   BIGINT DEFAULT 0,
    png_width       INTEGER DEFAULT 0,
    png_height      INTEGER DEFAULT 0,
    kgml_filename   TEXT,
    kgml_relpath    TEXT,
    kgml_file_size  BIGINT DEFAULT 0,
    node_count      INTEGER DEFAULT 0,
    gene_count      INTEGER DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ========================================================================
-- 7. gene_kegg_pathway  (基因-通路关联，去冗余)
-- ========================================================================
CREATE TABLE IF NOT EXISTS gene_kegg_pathway (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gene_id     TEXT NOT NULL REFERENCES gene_xref(gene_id) ON DELETE CASCADE,
    pathway_id  TEXT NOT NULL REFERENCES kegg_pathway_asset(pathway_id) ON DELETE CASCADE,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(gene_id, pathway_id)
);

CREATE INDEX IF NOT EXISTS idx_gene_kegg_pathway_gene_id    ON gene_kegg_pathway(gene_id);
CREATE INDEX IF NOT EXISTS idx_gene_kegg_pathway_pathway_id ON gene_kegg_pathway(pathway_id);

-- ========================================================================
-- 8. kegg_pathway_node
-- 保留原 SQLite id，确保 node_gene.node_id 引用正确。
-- ========================================================================
CREATE TABLE IF NOT EXISTS kegg_pathway_node (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pathway_id     TEXT NOT NULL REFERENCES kegg_pathway_asset(pathway_id) ON DELETE CASCADE,
    entry_id       TEXT NOT NULL,
    entry_type     TEXT,
    entry_name     TEXT,
    graphics_type  TEXT,
    x              INTEGER,
    y              INTEGER,
    width          INTEGER DEFAULT 0,
    height         INTEGER DEFAULT 0,
    left_x         INTEGER,
    top_y          INTEGER,
    right_x        INTEGER,
    bottom_y       INTEGER,
    raw_names      TEXT,
    link_url       TEXT,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(pathway_id, entry_id)
);

CREATE INDEX IF NOT EXISTS idx_kegg_pathway_node_pathway_id ON kegg_pathway_node(pathway_id);
CREATE INDEX IF NOT EXISTS idx_kegg_pathway_node_entry_id    ON kegg_pathway_node(entry_id);

-- ========================================================================
-- 9. kegg_pathway_node_gene
-- ========================================================================
CREATE TABLE IF NOT EXISTS kegg_pathway_node_gene (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pathway_id    TEXT NOT NULL,
    node_id       INTEGER NOT NULL REFERENCES kegg_pathway_node(id) ON DELETE CASCADE,
    kegg_gene_id  TEXT NOT NULL,
    gene_symbol   TEXT,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(node_id, kegg_gene_id)
);

CREATE INDEX IF NOT EXISTS idx_kegg_pathway_node_gene_node_id      ON kegg_pathway_node_gene(node_id);
CREATE INDEX IF NOT EXISTS idx_kegg_pathway_node_gene_kegg_gene_id ON kegg_pathway_node_gene(kegg_gene_id);
CREATE INDEX IF NOT EXISTS idx_kegg_pathway_node_gene_pathway_id   ON kegg_pathway_node_gene(pathway_id);

-- ========================================================================
-- 10. transcript_seq
-- ========================================================================
CREATE TABLE IF NOT EXISTS transcript_seq (
    transcript_acc       TEXT PRIMARY KEY,
    transcript_id       TEXT,
    gene_id             TEXT REFERENCES gene_xref(gene_id) ON DELETE CASCADE,
    seqid               TEXT,
    length              INTEGER,
    description         TEXT,
    seq                 TEXT
);

CREATE INDEX IF NOT EXISTS idx_transcript_seq_gene_id ON transcript_seq(gene_id);

-- ========================================================================
-- 11. cds_seq
-- ========================================================================
CREATE TABLE IF NOT EXISTS cds_seq (
    protein_id     TEXT PRIMARY KEY,
    gene_symbol    TEXT,
    seqid          TEXT,
    length         INTEGER,
    description    TEXT,
    seq            TEXT
);

-- ========================================================================
-- 12. protein_seq
-- ========================================================================
CREATE TABLE IF NOT EXISTS protein_seq (
    protein_id     TEXT PRIMARY KEY,
    length         INTEGER,
    description    TEXT,
    seq            TEXT
);

-- ========================================================================
-- 13. expression_sample  (36 个发育阶段样本元数据)
-- ========================================================================
CREATE TABLE IF NOT EXISTS expression_sample (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_name  TEXT NOT NULL UNIQUE,
    stage        TEXT NOT NULL,
    stage_label  TEXT NOT NULL,
    stage_order  INTEGER NOT NULL,
    sex          TEXT NOT NULL CHECK (sex IN ('Female', 'Male')),
    replicate    INTEGER NOT NULL CHECK (replicate BETWEEN 1 AND 3),
    UNIQUE(stage, sex, replicate)
);

CREATE INDEX IF NOT EXISTS idx_expression_sample_stage ON expression_sample(stage);
CREATE INDEX IF NOT EXISTS idx_expression_sample_sex  ON expression_sample(sex);

-- ========================================================================
-- 14. gene_expression  (宽表，23,147 基因 × 72 列)
-- 原始数值列保持 nullable（区分"缺失值"和"真实 0"）
-- ========================================================================
CREATE TABLE IF NOT EXISTS gene_expression (
    gene_id TEXT PRIMARY KEY REFERENCES gene_xref(gene_id) ON DELETE CASCADE,

    -- 36 FPKM 列
    e0_f1_fpkm   DOUBLE PRECISION, e0_f2_fpkm   DOUBLE PRECISION, e0_f3_fpkm   DOUBLE PRECISION,
    e0_m1_fpkm   DOUBLE PRECISION, e0_m2_fpkm   DOUBLE PRECISION, e0_m3_fpkm   DOUBLE PRECISION,
    e35_f1_fpkm  DOUBLE PRECISION, e35_f2_fpkm  DOUBLE PRECISION, e35_f3_fpkm  DOUBLE PRECISION,
    e35_m1_fpkm  DOUBLE PRECISION, e35_m2_fpkm  DOUBLE PRECISION, e35_m3_fpkm  DOUBLE PRECISION,
    e45_f1_fpkm  DOUBLE PRECISION, e45_f2_fpkm  DOUBLE PRECISION, e45_f3_fpkm  DOUBLE PRECISION,
    e45_m1_fpkm  DOUBLE PRECISION, e45_m2_fpkm  DOUBLE PRECISION, e45_m3_fpkm  DOUBLE PRECISION,
    e55_f1_fpkm  DOUBLE PRECISION, e55_f2_fpkm  DOUBLE PRECISION, e55_f3_fpkm  DOUBLE PRECISION,
    e55_m1_fpkm  DOUBLE PRECISION, e55_m2_fpkm  DOUBLE PRECISION, e55_m3_fpkm  DOUBLE PRECISION,
    e65_f1_fpkm  DOUBLE PRECISION, e65_f2_fpkm  DOUBLE PRECISION, e65_f3_fpkm  DOUBLE PRECISION,
    e65_m1_fpkm  DOUBLE PRECISION, e65_m2_fpkm  DOUBLE PRECISION, e65_m3_fpkm  DOUBLE PRECISION,
    e185_f1_fpkm DOUBLE PRECISION, e185_f2_fpkm DOUBLE PRECISION, e185_f3_fpkm DOUBLE PRECISION,
    e185_m1_fpkm DOUBLE PRECISION, e185_m2_fpkm DOUBLE PRECISION, e185_m3_fpkm DOUBLE PRECISION,

    -- 36 TPM 列
    e0_f1_tpm    DOUBLE PRECISION, e0_f2_tpm    DOUBLE PRECISION, e0_f3_tpm    DOUBLE PRECISION,
    e0_m1_tpm    DOUBLE PRECISION, e0_m2_tpm    DOUBLE PRECISION, e0_m3_tpm    DOUBLE PRECISION,
    e35_f1_tpm   DOUBLE PRECISION, e35_f2_tpm   DOUBLE PRECISION, e35_f3_tpm   DOUBLE PRECISION,
    e35_m1_tpm   DOUBLE PRECISION, e35_m2_tpm   DOUBLE PRECISION, e35_m3_tpm   DOUBLE PRECISION,
    e45_f1_tpm   DOUBLE PRECISION, e45_f2_tpm   DOUBLE PRECISION, e45_f3_tpm   DOUBLE PRECISION,
    e45_m1_tpm   DOUBLE PRECISION, e45_m2_tpm   DOUBLE PRECISION, e45_m3_tpm   DOUBLE PRECISION,
    e55_f1_tpm   DOUBLE PRECISION, e55_f2_tpm   DOUBLE PRECISION, e55_f3_tpm   DOUBLE PRECISION,
    e55_m1_tpm   DOUBLE PRECISION, e55_m2_tpm   DOUBLE PRECISION, e55_m3_tpm   DOUBLE PRECISION,
    e65_f1_tpm   DOUBLE PRECISION, e65_f2_tpm   DOUBLE PRECISION, e65_f3_tpm   DOUBLE PRECISION,
    e65_m1_tpm   DOUBLE PRECISION, e65_m2_tpm   DOUBLE PRECISION, e65_m3_tpm   DOUBLE PRECISION,
    e185_f1_tpm  DOUBLE PRECISION, e185_f2_tpm  DOUBLE PRECISION, e185_f3_tpm  DOUBLE PRECISION,
    e185_m1_tpm  DOUBLE PRECISION, e185_m2_tpm  DOUBLE PRECISION, e185_m3_tpm  DOUBLE PRECISION
);

-- 派生列：COALESCE 确保 GREATEST 不会因 NULL 返回 NULL
ALTER TABLE gene_expression
    ADD COLUMN IF NOT EXISTS max_fpkm DOUBLE PRECISION
    GENERATED ALWAYS AS (
        GREATEST(
            COALESCE(e0_f1_fpkm,0),  COALESCE(e0_f2_fpkm,0),  COALESCE(e0_f3_fpkm,0),
            COALESCE(e0_m1_fpkm,0),  COALESCE(e0_m2_fpkm,0),  COALESCE(e0_m3_fpkm,0),
            COALESCE(e35_f1_fpkm,0), COALESCE(e35_f2_fpkm,0), COALESCE(e35_f3_fpkm,0),
            COALESCE(e35_m1_fpkm,0), COALESCE(e35_m2_fpkm,0), COALESCE(e35_m3_fpkm,0),
            COALESCE(e45_f1_fpkm,0), COALESCE(e45_f2_fpkm,0), COALESCE(e45_f3_fpkm,0),
            COALESCE(e45_m1_fpkm,0), COALESCE(e45_m2_fpkm,0), COALESCE(e45_m3_fpkm,0),
            COALESCE(e55_f1_fpkm,0), COALESCE(e55_f2_fpkm,0), COALESCE(e55_f3_fpkm,0),
            COALESCE(e55_m1_fpkm,0), COALESCE(e55_m2_fpkm,0), COALESCE(e55_m3_fpkm,0),
            COALESCE(e65_f1_fpkm,0), COALESCE(e65_f2_fpkm,0), COALESCE(e65_f3_fpkm,0),
            COALESCE(e65_m1_fpkm,0), COALESCE(e65_m2_fpkm,0), COALESCE(e65_m3_fpkm,0),
            COALESCE(e185_f1_fpkm,0),COALESCE(e185_f2_fpkm,0),COALESCE(e185_f3_fpkm,0),
            COALESCE(e185_m1_fpkm,0),COALESCE(e185_m2_fpkm,0),COALESCE(e185_m3_fpkm,0)
        )
    ) STORED;

ALTER TABLE gene_expression
    ADD COLUMN IF NOT EXISTS max_tpm DOUBLE PRECISION
    GENERATED ALWAYS AS (
        GREATEST(
            COALESCE(e0_f1_tpm,0),  COALESCE(e0_f2_tpm,0),  COALESCE(e0_f3_tpm,0),
            COALESCE(e0_m1_tpm,0),  COALESCE(e0_m2_tpm,0),  COALESCE(e0_m3_tpm,0),
            COALESCE(e35_f1_tpm,0), COALESCE(e35_f2_tpm,0), COALESCE(e35_f3_tpm,0),
            COALESCE(e35_m1_tpm,0), COALESCE(e35_m2_tpm,0), COALESCE(e35_m3_tpm,0),
            COALESCE(e45_f1_tpm,0), COALESCE(e45_f2_tpm,0), COALESCE(e45_f3_tpm,0),
            COALESCE(e45_m1_tpm,0), COALESCE(e45_m2_tpm,0), COALESCE(e45_m3_tpm,0),
            COALESCE(e55_f1_tpm,0), COALESCE(e55_f2_tpm,0), COALESCE(e55_f3_tpm,0),
            COALESCE(e55_m1_tpm,0), COALESCE(e55_m2_tpm,0), COALESCE(e55_m3_tpm,0),
            COALESCE(e65_f1_tpm,0), COALESCE(e65_f2_tpm,0), COALESCE(e65_f3_tpm,0),
            COALESCE(e65_m1_tpm,0), COALESCE(e65_m2_tpm,0), COALESCE(e65_m3_tpm,0),
            COALESCE(e185_f1_tpm,0),COALESCE(e185_f2_tpm,0),COALESCE(e185_f3_tpm,0),
            COALESCE(e185_m1_tpm,0),COALESCE(e185_m2_tpm,0),COALESCE(e185_m3_tpm,0)
        )
    ) STORED;

CREATE INDEX IF NOT EXISTS idx_gene_expression_max_fpkm ON gene_expression(max_fpkm DESC);
CREATE INDEX IF NOT EXISTS idx_gene_expression_max_tpm  ON gene_expression(max_tpm DESC);

COMMIT;
