-- V007: Expression data staging layer for full traceability
-- Creates: import_batch, stg_update_expression_matrix, gene_source_mapping
--          stg_update_gene_annotation, stg_featurecounts_raw, stg_featurecounts_summary
--          stg_master_expression_table, import_qc_result
-- Adds: source_gene_count, curated_gene_count to dataset

BEGIN;

-- Add gene count columns to dataset
ALTER TABLE dataset ADD COLUMN IF NOT EXISTS source_gene_count INTEGER;
ALTER TABLE dataset ADD COLUMN IF NOT EXISTS curated_gene_count INTEGER;

-- 1. Import batch tracking
CREATE TABLE IF NOT EXISTS import_batch (
    batch_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_dir         TEXT NOT NULL,
    files_imported   TEXT[] NOT NULL,
    file_hashes      JSONB,
    source_gene_count INTEGER,
    mapped_gene_count INTEGER,
    unmapped_gene_count INTEGER,
    ambiguous_gene_count INTEGER,
    matrix_staging_rows BIGINT,
    total_staging_rows BIGINT,
    total_staging_rows_all_files BIGINT,
    total_fact_rows  BIGINT,
    import_script    TEXT,
    import_version   TEXT,
    status           TEXT NOT NULL DEFAULT 'running',
    started_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at     TIMESTAMPTZ,
    error_message    TEXT
);

COMMENT ON TABLE import_batch IS 'Tracks each data import run with full provenance';
COMMENT ON COLUMN import_batch.matrix_staging_rows IS 'Rows in stg_update_expression_matrix (4 matrix files)';
COMMENT ON COLUMN import_batch.total_staging_rows IS 'Legacy: same as matrix_staging_rows (backward compat)';
COMMENT ON COLUMN import_batch.total_staging_rows_all_files IS 'Total rows across ALL staging tables';

-- 2. Raw staging table — 100% of source matrix data, no mapping, no loss
-- source_gene_id_raw = original file value (never modified)
-- source_gene_id     = normalized (trimmed, empty→'.', comment lines preserved)
CREATE TABLE IF NOT EXISTS stg_update_expression_matrix (
    staging_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT NOT NULL REFERENCES import_batch(batch_id),
    source_file      TEXT NOT NULL,
    source_metric    TEXT NOT NULL,
    source_gene_id_raw TEXT NOT NULL,
    source_gene_id   TEXT NOT NULL,
    source_row_number INTEGER,
    sample_name      TEXT NOT NULL,
    raw_value_text   TEXT,
    value_numeric    DOUBLE PRECISION,
    is_valid         BOOLEAN NOT NULL DEFAULT TRUE,
    invalid_reason   TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE stg_update_expression_matrix IS 'Raw staging: 100% of source matrix data, no gene mapping applied';

CREATE INDEX IF NOT EXISTS idx_stg_update_batch ON stg_update_expression_matrix(batch_id);
CREATE INDEX IF NOT EXISTS idx_stg_update_gene ON stg_update_expression_matrix(source_gene_id);
CREATE INDEX IF NOT EXISTS idx_stg_update_metric ON stg_update_expression_matrix(source_metric);

-- 3. Gene source mapping audit
CREATE TABLE IF NOT EXISTS gene_source_mapping (
    mapping_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT NOT NULL REFERENCES import_batch(batch_id),
    source_gene_id   TEXT NOT NULL,
    canonical_gene_id TEXT,
    mapping_status   TEXT NOT NULL,
    mapping_method   TEXT,
    confidence       DOUBLE PRECISION DEFAULT 1.0,
    ambiguity_count  INTEGER DEFAULT 1,
    ambiguity_details JSONB,
    reason           TEXT,
    source_dataset   TEXT,
    metric_code      TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE gene_source_mapping IS 'Audit trail: source gene_id to canonical gene_id mapping with status and reason';
COMMENT ON COLUMN gene_source_mapping.metric_code IS 'Which metric file(s) this gene appears in (tpm/fpkm/normcount/raw_count or union)';

CREATE INDEX IF NOT EXISTS idx_gene_source_map_batch ON gene_source_mapping(batch_id);
CREATE INDEX IF NOT EXISTS idx_gene_source_map_src ON gene_source_mapping(source_gene_id);
CREATE INDEX IF NOT EXISTS idx_gene_source_map_status ON gene_source_mapping(mapping_status);

-- 4. Gene annotation staging (day_gene_annotation.tsv)
CREATE TABLE IF NOT EXISTS stg_update_gene_annotation (
    staging_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT NOT NULL REFERENCES import_batch(batch_id),
    source_file      TEXT NOT NULL,
    source_gene_id_raw TEXT NOT NULL,
    source_gene_id   TEXT NOT NULL,
    source_row_number INTEGER,
    chromosome       TEXT,
    start_pos        TEXT,
    end_pos          TEXT,
    strand           TEXT,
    gene_length      INTEGER,
    raw_line         TEXT,
    is_valid         BOOLEAN NOT NULL DEFAULT TRUE,
    invalid_reason   TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE stg_update_gene_annotation IS 'Gene annotation staging from day_gene_annotation.tsv (chr/start/end/strand/length)';

CREATE INDEX IF NOT EXISTS idx_stg_gene_annot_batch ON stg_update_gene_annotation(batch_id);
CREATE INDEX IF NOT EXISTS idx_stg_gene_annot_gene ON stg_update_gene_annotation(source_gene_id);

-- 5. featureCounts raw counts staging (day_featureCounts.txt)
CREATE TABLE IF NOT EXISTS stg_featurecounts_raw (
    staging_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT NOT NULL REFERENCES import_batch(batch_id),
    source_file      TEXT NOT NULL,
    source_gene_id   TEXT NOT NULL,
    source_row_number INTEGER,
    chromosome       TEXT,
    start_pos        TEXT,
    end_pos          TEXT,
    strand           TEXT,
    gene_length      INTEGER,
    sample_name      TEXT NOT NULL,
    sample_column_raw TEXT,
    raw_count_text   TEXT,
    raw_count_value  BIGINT,
    raw_line         TEXT,
    is_valid         BOOLEAN NOT NULL DEFAULT TRUE,
    invalid_reason   TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE stg_featurecounts_raw IS 'featureCounts raw output staging (all columns preserved)';
COMMENT ON COLUMN stg_featurecounts_raw.sample_column_raw IS 'Original BAM path column name from header (e.g. .../E0_Female1.bam)';
COMMENT ON COLUMN stg_featurecounts_raw.raw_line IS 'Original TSV line for full audit reproduction';

CREATE INDEX IF NOT EXISTS idx_stg_fcraw_batch ON stg_featurecounts_raw(batch_id);
CREATE INDEX IF NOT EXISTS idx_stg_fcraw_gene ON stg_featurecounts_raw(source_gene_id);

-- 6. featureCounts summary staging (day_featureCounts.txt.summary)
CREATE TABLE IF NOT EXISTS stg_featurecounts_summary (
    staging_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT NOT NULL REFERENCES import_batch(batch_id),
    source_file      TEXT NOT NULL,
    status_category  TEXT NOT NULL,
    sample_values    JSONB NOT NULL,
    raw_line         TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE stg_featurecounts_summary IS 'featureCounts assignment summary per sample';

CREATE INDEX IF NOT EXISTS idx_stg_fcsumm_batch ON stg_featurecounts_summary(batch_id);

-- 7. Master expression table staging (day_master_expression_table.tsv)
CREATE TABLE IF NOT EXISTS stg_master_expression_table (
    staging_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT NOT NULL REFERENCES import_batch(batch_id),
    source_file      TEXT NOT NULL,
    source_gene_id_raw TEXT NOT NULL,
    source_gene_id   TEXT NOT NULL,
    source_row_number INTEGER,
    gene_name        TEXT,
    raw_values       JSONB NOT NULL,
    raw_line         TEXT,
    is_valid         BOOLEAN NOT NULL DEFAULT TRUE,
    invalid_reason   TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE stg_master_expression_table IS 'Master expression table staging (wide format, all metrics in one row)';

CREATE INDEX IF NOT EXISTS idx_stg_master_batch ON stg_master_expression_table(batch_id);
CREATE INDEX IF NOT EXISTS idx_stg_master_gene ON stg_master_expression_table(source_gene_id);

-- 8. Import QC result table
CREATE TABLE IF NOT EXISTS import_qc_result (
    qc_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT NOT NULL REFERENCES import_batch(batch_id),
    file_name        TEXT NOT NULL,
    file_hash        TEXT,
    qc_type          TEXT NOT NULL,
    qc_name          TEXT NOT NULL,
    expected_value   TEXT,
    actual_value     TEXT,
    passed           BOOLEAN NOT NULL,
    details          JSONB,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE import_qc_result IS 'Per-file QC assertions recorded during import';

CREATE INDEX IF NOT EXISTS idx_qc_batch ON import_qc_result(batch_id);
CREATE INDEX IF NOT EXISTS idx_qc_file ON import_qc_result(file_name);
CREATE INDEX IF NOT EXISTS idx_qc_passed ON import_qc_result(passed);

COMMIT;
