-- V009: Comparative genomics tables for GRCg6a vs GRCg7b
-- Creates: genome_assembly, synteny_block, gene_coordinate_mapping, chromosome_mapping

BEGIN;

-- 1. Genome assembly registry
CREATE TABLE IF NOT EXISTS genome_assembly (
    assembly_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_name   TEXT NOT NULL UNIQUE,
    species         TEXT NOT NULL,
    accession       TEXT,
    version         TEXT,
    release_date    DATE,
    chromosome_count INTEGER,
    total_length    BIGINT,
    gene_count      INTEGER,
    description     TEXT,
    fasta_path      TEXT,
    gff_path        TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE genome_assembly IS 'Registry of genome assemblies for comparative genomics';

-- Insert default assemblies
INSERT INTO genome_assembly (assembly_name, species, accession, version, description)
VALUES
    ('GRCg6a', 'Gallus gallus', 'GCF_000002315.6', '6a', 'White Leghorn reference genome'),
    ('GRCg7b', 'Gallus gallus', 'GCF_016699485.2', '7b', 'Broiler reference genome (bGalGal1)')
ON CONFLICT (assembly_name) DO NOTHING;

-- 2. Chromosome mapping between assemblies
CREATE TABLE IF NOT EXISTS chromosome_mapping (
    mapping_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_from   TEXT NOT NULL,
    assembly_to     TEXT NOT NULL,
    chr_from        TEXT NOT NULL,
    chr_to          TEXT NOT NULL,
    refseq_from     TEXT,
    refseq_to       TEXT,
    genbank_from    TEXT,
    genbank_to      TEXT,
    strand          CHAR(1) DEFAULT '+',
    score           DOUBLE PRECISION,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE chromosome_mapping IS 'Chromosome-level mapping between genome assemblies';

CREATE INDEX IF NOT EXISTS idx_chr_mapping_from ON chromosome_mapping(assembly_from, chr_from);
CREATE INDEX IF NOT EXISTS idx_chr_mapping_to ON chromosome_mapping(assembly_to, chr_to);

-- 3. Synteny blocks (from BLAST/minimap2)
CREATE TABLE IF NOT EXISTS synteny_block (
    block_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_1      TEXT NOT NULL,
    assembly_2      TEXT NOT NULL,
    chr_1           TEXT NOT NULL,
    start_1         INTEGER NOT NULL,
    end_1           INTEGER NOT NULL,
    chr_2           TEXT NOT NULL,
    start_2         INTEGER NOT NULL,
    end_2           INTEGER NOT NULL,
    strand          CHAR(1) DEFAULT '+',
    score           DOUBLE PRECISION,
    e_value         DOUBLE PRECISION,
    identity        DOUBLE PRECISION,
    alignment_length INTEGER,
    gene_count      INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE synteny_block IS 'Synteny blocks between genome assemblies from whole-genome alignment';

CREATE INDEX IF NOT EXISTS idx_synteny_block_1 ON synteny_block(assembly_1, chr_1, start_1, end_1);
CREATE INDEX IF NOT EXISTS idx_synteny_block_2 ON synteny_block(assembly_2, chr_2, start_2, end_2);
CREATE INDEX IF NOT EXISTS idx_synteny_score ON synteny_block(score DESC);

-- 4. Gene coordinate mapping (cross-assembly)
CREATE TABLE IF NOT EXISTS gene_coordinate_mapping (
    mapping_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gene_id         TEXT NOT NULL,
    gene_symbol     TEXT,
    assembly_from   TEXT NOT NULL,
    assembly_to     TEXT NOT NULL,
    chr_from        TEXT NOT NULL,
    start_from      INTEGER NOT NULL,
    end_from        INTEGER NOT NULL,
    strand_from     CHAR(1),
    chr_to          TEXT NOT NULL,
    start_to        INTEGER NOT NULL,
    end_to          INTEGER NOT NULL,
    strand_to       CHAR(1),
    mapping_method  TEXT,
    confidence      DOUBLE PRECISION DEFAULT 1.0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE gene_coordinate_mapping IS 'Gene-level coordinate mapping between assemblies via NCBI GeneID';

CREATE INDEX IF NOT EXISTS idx_gene_coord_gene ON gene_coordinate_mapping(gene_id);
CREATE INDEX IF NOT EXISTS idx_gene_coord_from ON gene_coordinate_mapping(assembly_from, chr_from, start_from, end_from);
CREATE INDEX IF NOT EXISTS idx_gene_coord_to ON gene_coordinate_mapping(assembly_to, chr_to, start_to, end_to);

-- 5. PAF alignment data (raw alignments)
CREATE TABLE IF NOT EXISTS paf_alignment (
    alignment_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_1      TEXT NOT NULL,
    assembly_2      TEXT NOT NULL,
    query_name      TEXT NOT NULL,
    query_length    INTEGER NOT NULL,
    query_start     INTEGER NOT NULL,
    query_end       INTEGER NOT NULL,
    strand          CHAR(1),
    target_name     TEXT NOT NULL,
    target_length   INTEGER NOT NULL,
    target_start    INTEGER NOT NULL,
    target_end      INTEGER NOT NULL,
    residue_matches INTEGER,
    alignment_length INTEGER,
    mapping_quality INTEGER,
    score           DOUBLE PRECISION,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE paf_alignment IS 'Raw PAF-format alignments for synteny visualization';

CREATE INDEX IF NOT EXISTS idx_paf_query ON paf_alignment(assembly_1, query_name, query_start, query_end);
CREATE INDEX IF NOT EXISTS idx_paf_target ON paf_alignment(assembly_2, target_name, target_start, target_end);

COMMIT;
